### ISSUE TITLE
Help to compile raylib.a under windows

### ISSUE THREAD

**Issue by GuvaCode** [sysrpl/Raylib.4.0.Pascal#1]
Hi Anthony Walter !!!
could you tell me how you compiled libraylib-win64.a.
I've already spent all my brains. I have errors under Windows when linking. And with your libraylib-win64.a everything links.

But I need the latest version of ray gui. on linux there are no problems with compilation and linking.
And windows 10 is not how it does not work.

**Comment by sysrpl** [comment]
Just for your information, I use mingw64 to build libraylib-win64.a.
